const:
  solar_const: 1365.2
  stef_boltz_const: 5.6704e-8

dirs:
  output: 'output'
  tmp: 'tmp'

grid:
  dlat_deg: 1.
  dtime_days: 5.
  num_ann_cycle_points: 12
  num_vert_levels: 30
  num_days: 2000.

albedo: 0.3

model:
  day_type: 2
  dry_atmos: False
  lapse_rate: 6.5
  mixed_layer_depth: 1.

runtime:
  quiet: False
  temp_min_valid: 150.
  temp_max_valid: 340.

str:
  day_str: 'day'
  lat_str: 'lat'
  lev_str: 'lev'
  time_str: 'time'
