import numpy as np

DAYS_OF_YEAR = range(15, 356, 30)
DLAT = 1
LATS = np.arange(-90+0.5*DLAT, 90-0.49*DLAT, DLAT)

configfile: "config.yaml"

rule rce_one_lat:
    output:
        temp("tmp/lat_{lat}/solar_lon_{day_of_year}.nc")
    shell:
        "./rce_climlab.py --lat={wildcards.lat} "
        "--day-of-year={wildcards.day_of_year} "
        "--path-output={output} "
        "--write-to-disk"

rule rce_mult_lats:
    input:
        expand("tmp/lat_{lat}/solar_lon_{{day_of_year}}.nc", lat=LATS)
    output:
        "out/solar_lon_{day_of_year}.nc"
    run:
        import xarray as xr
        ds = xr.open_mfdataset(input[:],
                               concat_dim=config['lat_str']).transpose()
        ds.to_netcdf(output[0])


rule rce_ann_cycle:
    input:
        expand("out/solar_lon_{day}.nc", day=DAYS_OF_YEAR)
